version: 0.2

env:
  variables:
    IMAGE_NAME: "puntosdeaccesodockerimg"

phases:
  build:
    commands:
      - echo "Login to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <account-id>.dkr.ecr.<region>.amazonaws.com
      - echo "Logged in to ECR..."
      - echo "Building Docker image..."
      - docker build -t $IMAGE_NAME .
      - echo "Tagging Docker image with source version..."
      - docker tag $IMAGE_NAME $ECR_REPO_URL/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - ECHO "Docker image pushed"
      



      