# Generated by Django 4.2.10 on 2024-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDeAccesoWifi',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=50)),
                ('fecha_instalacion', models.DateField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('colonia', models.CharField(max_length=100)),
                ('alcaldia', models.CharField(max_length=50)),
            ],
        ),
    ]
